# Generated by Django 5.0.1 on 2024-03-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AshaWorker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='takslist',
            new_name='tasklist',
        ),
    ]
