# Generated by Django 5.0.1 on 2024-03-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AshaWorker', '0002_rename_takslist_tasklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tasklist',
        ),
    ]
