# Generated by Django 5.0.1 on 2024-02-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(max_length=30)),
                ('kitchen_contact', models.CharField(max_length=30)),
                ('kitchen_address', models.CharField(max_length=30)),
                ('kitchen_email', models.EmailField(max_length=30)),
                ('kitchen_password', models.CharField(max_length=30)),
            ],
        ),
    ]
