# Generated by Django 5.0.1 on 2024-03-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ward', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_kitchen',
        ),
    ]
