# Generated by Django 5.0.1 on 2024-02-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCenter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_medicinerequest',
        ),
    ]
