# Generated by Django 5.0.1 on 2024-02-15 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCenter', '0002_delete_tbl_medicinerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_medicinerequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_prescription', models.CharField(max_length=30)),
                ('medicine_date', models.DateField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthCenter.tbl_patient')),
            ],
        ),
    ]
