# Generated by Django 5.0.1 on 2024-02-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCenter', '0004_remove_tbl_patient_patient_admitdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_medicinerequest',
            name='patient_id',
        ),
        migrations.DeleteModel(
            name='tbl_patient',
        ),
    ]
