# Generated by Django 5.0.1 on 2024-02-17 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCenter', '0005_remove_tbl_medicinerequest_patient_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('patient_age', models.CharField(max_length=30)),
                ('patient_gender', models.CharField(max_length=30)),
                ('patient_admitdate', models.CharField(max_length=30)),
                ('patient_dischargedate', models.CharField(max_length=30)),
                ('patient_ward', models.CharField(max_length=50)),
                ('patient_vstatus', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='tbl_medicinerequest',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthCenter.tbl_patient'),
        ),
    ]
