# Generated by Django 5.0.1 on 2024-02-23 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCenter', '0006_tbl_patient_tbl_medicinerequest_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_foodrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_date', models.DateField(auto_now_add=True)),
                ('food_status', models.CharField(max_length=20)),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthCenter.tbl_patient')),
            ],
        ),
    ]
