# Generated by Django 5.0.1 on 2024-03-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCenter', '0008_remove_tbl_medicinerequest_patient_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_medicinerequest',
            new_name='tbl_medicinelist',
        ),
        migrations.DeleteModel(
            name='tbl_foodrequest',
        ),
    ]
