# Generated by Django 5.0.1 on 2024-03-05 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_healthcenter'),
        ('HealthCenter', '0009_rename_tbl_medicinerequest_tbl_medicinelist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_medicinelist',
            name='Healthcenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_healthcenter'),
        ),
    ]
