# Generated by Django 5.0.1 on 2024-03-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCenter', '0011_alter_tbl_patient_patient_admitdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_patient',
        ),
    ]
