# Generated by Django 5.0.1 on 2024-03-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCenter', '0013_tbl_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_patient',
            name='patient_contact',
            field=models.IntegerField(),
        ),
    ]
