# Generated by Django 5.0.1 on 2024-03-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCenter', '0014_alter_tbl_patient_patient_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_medicinelist',
        ),
    ]
