# Generated by Django 5.0.1 on 2024-03-14 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_tbl_healthcenter'),
        ('HealthCenter', '0015_delete_tbl_medicinelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_medicinelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_prescription', models.CharField(max_length=30)),
                ('medicine_date', models.DateField(auto_now_add=True)),
                ('Healthcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_healthcenter')),
            ],
        ),
    ]
