# Generated by Django 5.0.1 on 2024-02-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ashaworker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=30)),
                ('worker_gender', models.CharField(max_length=30)),
                ('worker_ward', models.CharField(max_length=30)),
                ('worker_address', models.CharField(max_length=30)),
                ('worker_proof', models.CharField(max_length=30)),
                ('worker_photo', models.FileField(upload_to='images/')),
                ('worker_email', models.CharField(max_length=30)),
                ('worker_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_healthcenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=30)),
                ('center_gender', models.CharField(max_length=30)),
                ('center_ward', models.CharField(max_length=30)),
                ('center_address', models.CharField(max_length=30)),
                ('center_proof', models.FileField(upload_to='images/')),
                ('center_photo', models.FileField(upload_to='images/')),
                ('center_email', models.CharField(max_length=30)),
                ('center_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_photo', models.FileField(upload_to='images/')),
                ('user_dob', models.CharField(max_length=30)),
                ('user_gender', models.CharField(max_length=30)),
                ('user_ward', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=30)),
                ('user_proof', models.FileField(upload_to='images/')),
                ('user_email', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_viraldiseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=30)),
                ('disease_mode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_wardmember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=30)),
                ('member_gender', models.CharField(max_length=30)),
                ('member_ward', models.CharField(max_length=30)),
                ('member_address', models.CharField(max_length=30)),
                ('member_proof', models.CharField(max_length=30)),
                ('member_photo', models.FileField(upload_to='images/')),
                ('member_email', models.CharField(max_length=30)),
                ('member_password', models.CharField(max_length=30)),
            ],
        ),
    ]
