# Generated by Django 5.0.1 on 2024-02-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_kitchencenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(max_length=30)),
                ('kitchen_ward', models.CharField(max_length=30)),
                ('kitchen_address', models.CharField(max_length=30)),
                ('kitchen_photo', models.FileField(upload_to='images/')),
                ('kitchen_email', models.CharField(max_length=30)),
                ('kitchen_password', models.CharField(max_length=30)),
            ],
        ),
    ]
