# Generated by Django 5.0.1 on 2024-03-02 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_admin'),
        ('Guest', '0002_tbl_kitchencenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_ashaworker',
            name='worker_ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward'),
        ),
        migrations.AlterField(
            model_name='tbl_healthcenter',
            name='center_ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward'),
        ),
        migrations.AlterField(
            model_name='tbl_kitchencenter',
            name='kitchen_ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward'),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward'),
        ),
        migrations.AlterField(
            model_name='tbl_wardmember',
            name='member_ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward'),
        ),
    ]
