# Generated by Django 5.0.1 on 2024-03-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_alter_tbl_ashaworker_worker_ward_and_more'),
        ('User', '0004_remove_tbl_sendcomplaint_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_ashaworker',
            name='worker_ward',
        ),
        migrations.RemoveField(
            model_name='tbl_healthcenter',
            name='center_ward',
        ),
        migrations.RemoveField(
            model_name='tbl_kitchencenter',
            name='kitchen_ward',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_ward',
        ),
        migrations.DeleteModel(
            name='tbl_viraldiseases',
        ),
        migrations.RemoveField(
            model_name='tbl_wardmember',
            name='member_ward',
        ),
        migrations.DeleteModel(
            name='tbl_ashaworker',
        ),
        migrations.DeleteModel(
            name='tbl_healthcenter',
        ),
        migrations.DeleteModel(
            name='tbl_kitchencenter',
        ),
        migrations.DeleteModel(
            name='tbl_user',
        ),
        migrations.DeleteModel(
            name='tbl_wardmember',
        ),
    ]
