# Generated by Django 5.0.1 on 2024-03-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_healthcenter',
        ),
    ]
