# Generated by Django 5.0.1 on 2024-03-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_alter_tbl_healthcenter_center_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_healthcenter',
            name='center_photo',
            field=models.FileField(default='user.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tbl_healthcenter',
            name='center_proof',
            field=models.FileField(default='user.png', upload_to='images/'),
        ),
    ]
