# Generated by Django 5.0.1 on 2024-03-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_alter_tbl_healthcenter_center_photo_and_more'),
        ('HealthCenter', '0015_delete_tbl_medicinelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_healthcenter',
        ),
    ]
