# Generated by Django 5.0.1 on 2024-03-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_tbl_healthcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_healthcenter',
            name='center_photo',
            field=models.FileField(default='images/user.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tbl_healthcenter',
            name='center_proof',
            field=models.FileField(default='images/user.png', upload_to='images/'),
        ),
    ]
