# Generated by Django 5.0.1 on 2024-03-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_tbl_sendcomplaint_complaint_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_sendcomplaint',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_userfeedback',
            name='user_id',
        ),
    ]
