# Generated by Django 5.0.1 on 2024-03-02 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_initial'),
        ('User', '0004_remove_tbl_sendcomplaint_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_sendcomplaint',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
        migrations.AddField(
            model_name='tbl_userfeedback',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
