# Generated by Django 5.0.1 on 2024-03-02 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCenter', '0009_rename_tbl_medicinerequest_tbl_medicinelist_and_more'),
        ('User', '0005_tbl_sendcomplaint_user_id_tbl_userfeedback_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_foodrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_date', models.DateField(auto_now_add=True)),
                ('food_status', models.CharField(max_length=20)),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthCenter.tbl_patient')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_medicinerequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_prescription', models.CharField(max_length=30)),
                ('medicine_date', models.DateField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthCenter.tbl_patient')),
            ],
        ),
    ]
