# Generated by Django 5.0.1 on 2024-03-03 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_healthcenter'),
        ('User', '0007_remove_tbl_medicinerequest_patient_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_foodrequest',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='tbl_foodrequest',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
