# Generated by Django 5.0.1 on 2024-03-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_tbl_foodrequest_patient_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_foodrequest',
        ),
    ]
