# Generated by Django 5.0.1 on 2024-03-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_tbl_foodrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_medicinerequest',
        ),
    ]
