# Generated by Django 5.0.1 on 2024-03-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_alter_tbl_healthcenter_center_photo_and_more'),
        ('User', '0013_remove_tbl_foodrequest_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_foodrequest',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
        migrations.AddField(
            model_name='tbl_medicinerequest',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
        migrations.AddField(
            model_name='tbl_sendcomplaint',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
        migrations.AddField(
            model_name='tbl_userfeedback',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
