# Generated by Django 5.0.1 on 2024-03-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitchencenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_address', models.CharField(max_length=50)),
                ('patient_ward', models.CharField(max_length=50)),
                ('task_date', models.DateField(blank=True, null=True)),
                ('task_status', models.IntegerField(default=0)),
            ],
        ),
    ]
