# Generated by Django 5.0.1 on 2024-03-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitchencenter', '0003_rename_tasklist_tbl_tasklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_tasklist',
            name='task_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
