# Generated by Django 5.0.1 on 2024-03-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kitchencenter', '0004_alter_tbl_tasklist_task_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_tasklist',
        ),
    ]
