# Generated by Django 5.0.1 on 2024-03-05 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_healthcenter'),
        ('Kitchencenter', '0007_alter_tbl_tasklist_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_foodlist',
            name='kitchen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_kitchencenter'),
        ),
    ]
